### ISSUE TITLE
If report processing fails, metrics data is broken in the next report

### ISSUE THREAD

**Issue by funamoto** [ultrabrew/metrics#9]
### Problem
* If report processing(flush) fails, metrics data is broken in the next report
(e.g. HTTP disconnection error) 

### Cause
* Because the `byteBuffer#position` is not restored or clear is not executed.
https://github.com/ultrabrew/metrics/blob/e1e38520ca5332def16801e37eec111aa8efede2/reporter-influxdb/src/main/java/io/ultrabrew/metrics/reporters/influxdb/InfluxDBClient.java#L116-L124

### Possible Solution
1. If the report fails after `byteBuffer.flip`, return the `byteBuffer#position` to it's previous value
1. Always `byteBuffer.clear`

I think that the plan `1` is good.
How do you think about it?

**Comment by mmannerm** [comment]
1. should work if you also flip it back

**Comment by lonemeow** [comment]
The corrupted data is actually caused by another bug which would always send the entire buffer instead of just the used part of it, this bug just made it more visible.

Proposal 1 does not work, the issue isn't only the position but also the limit of the `ByteBuffer`. Also `ByteBuffer.flip()` can't be undone with another flip, although it can be undone by handcrafting the correct sequence of operations.

To be consistent, the proposed fix in the PR handles this case exactly like it does HTTP errors as code elsewhere expects that after a `flush()` call the buffer has more room - if it is desirable to keep the unsent data then some more work is required to make the rest of the code DTRT even if `flush()` can't make room in the buffer.
